spring.application.name=embabel


embabel.agent.platform.models.gemini.api-key=AIzaSyAxaDzUq7h4PXms0PuAa2lxQgJJDu7rnns
embabel.agent.platform.models.gemini.base-url=https://generativelanguage.googleapis.com/v1beta/openai
embabel.models.default-llm=gemini-3-flash-preview
embabel.models.llms.reviewer=gemini-3.1-pro-preview